discord:
  token: ${DISCORD_BOT_TOKEN}

server:
  port: ${DISCORD_SERVICE_PORT:8079}

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

xyz:
  vaillant:
    poc:
      front:
        service:
          url: ${FRONT_SERVICE_URL:http://localhost:3000}
      domain:
        service:
          url: ${BACK_SERVICE_URL:http://localhost:8080}
      discord:
        service:
          url: ${DISCORD_SERVICE_URL:http://localhost:8079}